// This file is generated by build.rs"
include!(concat!(env!("OUT_DIR"), "/resources.rs"));

pub fn resource_id() -> u64 {
    RESOURCE_ID
}

// per-user
pub fn resource_root(uid: u32) -> std::path::PathBuf {
    std::env::temp_dir().join(format!("stone-cli-{}", uid))
}

// per-resource snapshot
pub fn resource_dir(uid: u32) -> std::path::PathBuf {
    resource_root(uid).join(format!("{:x}", resource_id()))
}

pub fn resource_tar() -> &'static [u8] {
    RESOURCE_TAR
}
